import { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from 'app/store';

import Button from '@mui/material/Button';

const Home: NextPage = () => {
	const user = useSelector((state: RootState) => state.user);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Button variant="text">Text</Button>
				<Button variant="contained">Contained</Button>
				<Button variant="outlined">Outlined</Button>
				<Button>Primary</Button>
				<Button disabled>Disabled</Button>
				<Button href="#text-buttons">Link</Button>
			</main>
		</div>
	);
};

export default Home;
