import type { NextPage } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";
import { RootState } from "app/store";
import Link from "next/link";
import Button from "@mui/material/Button";
import BasicLayout from "components/common/BasicLayout";

const Index: NextPage = () => {
  const user = useSelector((state: RootState) => state.user);

  return (
    <BasicLayout headerTitle="main" back={true} footer={false}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Button variant="text">Text</Button>
          <Button variant="contained">Contained</Button>
          <Button variant="outlined">Outlined</Button>
          <Button>Primary</Button>
          <Button disabled>Disabled</Button>
          <Button href="#text-buttons">Link</Button>
          <Link href="/login">
            <a>login</a>
          </Link>
          <Link href="/app-bar">
            <a>Home</a>
          </Link>
        </main>
      </div>
    </BasicLayout>
  );
};

export default Index;
